In [1]:
import pandas as pd 
import numpy as np 
from sklearn.feature_extraction import text
from sklearn.metrics.pairwise import cosine_similarity

data = pd.read_csv('Instagram_data.csv')
data.head()

,Date,Impressions,From Home,From Hashtags,From Explore,From Other,Saves,Comments,Shares,Likes,Profile Visits,Follows,Conversion Rate,Caption,Hashtags
0,2021-12-10,3920,2586,1028,619,56,98,9,5,162,35,2,5.714286,Here are some of the most important data visua...,#finance #money #business #investing #investme...
1,2021-12-11,5394,2727,1838,1174,78,194,7,14,224,48,10,20.833333,Here are some of the best data science project...,#healthcare #health #covid #data #datascience ...
2,2021-12-12,4021,2085,1188,0,533,41,11,1,131,62,12,19.354839,Learn how to train a machine learning model an...,#data #datascience #dataanalysis #dataanalytic...
3,2021-12-13,4528,2700,621,932,73,172,10,7,213,23,8,34.782609,Here’s how you can write a Python program to d...,#python #pythonprogramming #pythonprojects #py...
4,2021-12-14,2518,1704,255,279,37,96,5,4,123,8,0,0.000000,Plotting annotations while visualizing your da...,#datavisualization #datascience #data #dataana...

In [5]:
data.columns

Index(['Date', 'Impressions', 'From Home', 'From Hashtags', 'From Explore',
       'From Other', 'Saves', 'Comments', 'Shares', 'Likes', 'Profile Visits',
       'Follows', 'Conversion Rate', 'Caption', 'Hashtags'],
      dtype='object')

In [2]:
features = ["Hashtags", "Caption"]
data = data[features]
data.head()

,Hashtags,Caption
0,#finance #money #business #investing #investme...,Here are some of the most important data visua...
1,#healthcare #health #covid #data #datascience ...,Here are some of the best data science project...
2,#data #datascience #dataanalysis #dataanalytic...,Learn how to train a machine learning model an...
3,#python #pythonprogramming #pythonprojects #py...,Here’s how you can write a Python program to d...
4,#datavisualization #datascience #data #dataana...,Plotting annotations while visualizing your da...

In [5]:
captions = data["Caption"].tolist()
uni_tfidf = text.TfidfVectorizer(input = captions, stop_words='english')
uni_matrix = uni_tfidf.fit_transform(captions)
uni_sim = cosine_similarity(uni_matrix)

def recommend(x):
    return ','.join(data["Caption"].loc[x.argsort()[-5:-1]])

data["Recommendation"] = [recommend(x) for x in uni_sim]
data.head()

,Hashtags,Caption,Recommendation
0,#finance #money #business #investing #investme...,Here are some of the most important data visua...,Here are some of the most important tools that...
1,#healthcare #health #covid #data #datascience ...,Here are some of the best data science project...,Here are some of the best data science project...
2,#data #datascience #dataanalysis #dataanalytic...,Learn how to train a machine learning model an...,Data Science Use Cases: Here’s how Zomato is u...
3,#python #pythonprogramming #pythonprojects #py...,Here’s how you can write a Python program to d...,Here’s how to write a Python function to rever...
4,#datavisualization #datascience #data #dataana...,Plotting annotations while visualizing your da...,Practice these 90+ Data Science Projects For B...

In [7]:
data["Recommendation"][1]

'Here are some of the best data science project ideas on the Economy. If you want to learn the use of Data Science in Economics, you should try these data science projects.,Here are some of the best Data Science project ideas on Healthcare and Fitness that you should try.,Here are some of the best data science project ideas on healthcare. If you want to become a data science professional in the healthcare domain then you must try to work on these projects.,Here are some of the best data science project ideas on healthcare. If you want to become a data science professional in the healthcare domain then you must try to work on these projects.'